//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码由 xsd 自动生成, Version=4.6.81.0。
// 
namespace Manage.Service.MongoDb {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="Manage.Service.MongoDb", IsNullable=false)]
    public partial class rules {
        
        private rulesCommands commandsField;
        
        private rulesOutputs outputsField;
        
        /// <remarks/>
        public rulesCommands commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
        
        /// <remarks/>
        public rulesOutputs outputs {
            get {
                return this.outputsField;
            }
            set {
                this.outputsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class rulesCommands {
        
        private command[] caseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("case")]
        public command[] @case {
            get {
                return this.caseField;
            }
            set {
                this.caseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(composedCommand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(singleCommand))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customCommand))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public abstract partial class command {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class output {
        
        private outputSupportCommands supportCommandsField;
        
        private script transformScriptField;
        
        /// <remarks/>
        public outputSupportCommands supportCommands {
            get {
                return this.supportCommandsField;
            }
            set {
                this.supportCommandsField = value;
            }
        }
        
        /// <remarks/>
        public script transformScript {
            get {
                return this.transformScriptField;
            }
            set {
                this.transformScriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class outputSupportCommands {
        
        private string[] commandNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commandName", DataType="token")]
        public string[] commandName {
            get {
                return this.commandNameField;
            }
            set {
                this.commandNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class script {
        
        private string bodyField;
        
        private scriptImports importsField;
        
        /// <remarks/>
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public scriptImports imports {
            get {
                return this.importsField;
            }
            set {
                this.importsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class scriptImports {
        
        private scriptImportsNameSpaces nameSpacesField;
        
        private scriptImportsAssemblies assembliesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public scriptImportsNameSpaces nameSpaces {
            get {
                return this.nameSpacesField;
            }
            set {
                this.nameSpacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public scriptImportsAssemblies assemblies {
            get {
                return this.assembliesField;
            }
            set {
                this.assembliesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class scriptImportsNameSpaces {
        
        private string[] addField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("add", DataType="token")]
        public string[] add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class scriptImportsAssemblies {
        
        private assemblyInfo[] addField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("add")]
        public assemblyInfo[] add {
            get {
                return this.addField;
            }
            set {
                this.addField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fileLocatedAssemblyInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(longNameLocatedAssemblyInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public abstract partial class assemblyInfo {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class fileLocatedAssemblyInfo : assemblyInfo {
        
        private string assemblyPathField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string assemblyPath {
            get {
                return this.assemblyPathField;
            }
            set {
                this.assemblyPathField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class longNameLocatedAssemblyInfo : assemblyInfo {
        
        private string assemblyNameField;
        
        /// <remarks/>
        public string assemblyName {
            get {
                return this.assemblyNameField;
            }
            set {
                this.assemblyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class composedCommand : command {
        
        private composedCommandCommands commandsField;
        
        /// <remarks/>
        public composedCommandCommands commands {
            get {
                return this.commandsField;
            }
            set {
                this.commandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class composedCommandCommands {
        
        private composedCommandCommandsCommand[] commandField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("command")]
        public composedCommandCommandsCommand[] command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class composedCommandCommandsCommand {
        
        private string nameField;
        
        private script linkNextScriptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public script linkNextScript {
            get {
                return this.linkNextScriptField;
            }
            set {
                this.linkNextScriptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(customCommand))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class singleCommand : command {
        
        private string templateField;
        
        private singleCommandRequires requiresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public singleCommandRequires requires {
            get {
                return this.requiresField;
            }
            set {
                this.requiresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class singleCommandRequires {
        
        private string[] keyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("key", DataType="token")]
        public string[] key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Manage.Service.MongoDb")]
    public partial class customCommand : singleCommand {
        
        private string customCommandNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string customCommandName {
            get {
                return this.customCommandNameField;
            }
            set {
                this.customCommandNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="Manage.Service.MongoDb")]
    public partial class rulesOutputs {
        
        private output[] caseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("case")]
        public output[] @case {
            get {
                return this.caseField;
            }
            set {
                this.caseField = value;
            }
        }
    }
}
